### ISSUE TITLE
Support for MacOS or Linux

### ISSUE THREAD

**Issue by HCharlie** [billpwchan/futu_algo#30]
Hi there, is it possible for the project to run on Mac OS or Linux system? Or any plan for this?

**Comment by billpwchan** [comment]
Thanks for the message! 

I think the code itself should be okay for running on Linux, but since I'm relying on Futu OpenD on Windows, there may be some minor changes needed for this to work fully on other OS. 

One example can be the auto-invocation of OpenD on Windows, in which if you're running this on another OS, you have to change/remove this part of code so that it will not try to call an executable program from a directory that only exists in Windows.

**Comment by billpwchan** [comment]
Updated all path-related code to Pathlib with better support for Mac OS and Linux system. Thanks!
